version: '3.9'
services:
  backend:
    build:
      context: ./docker
      dockerfile: backend.Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./backend:/go/src/myapp
    command: "air"
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env
    networks:
      - esnet

  frontend:
    image: node:20.12.2
    working_dir: /home/node/myapp
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/home/node/myapp
      - /home/node/myapp/node_modules
    command: "bash -c 'npm i && npm run dev'"
    environment:
      TZ: Asia/Tokyo
    networks:
      - esnet

  db:
    build:
      context: ./docker
      dockerfile: mysql.Dockerfile
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sql:/sqlscripts
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=training
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "root"
        ]
      interval: 1s
      timeout: 1s
      retries: 6
      start_period: 2s
    networks:
      - esnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - esnet
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cat/health | grep -e green -e yellow"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: > # 日本語検索用の Analyzer を設定する
      bash -c '
        bin/elasticsearch-plugin install analysis-icu
        bin/elasticsearch-plugin install analysis-kuromoji
        echo "y" | bin/elasticsearch-systemd-pre-exec
        exec docker-entrypoint.sh elasticsearch'

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - esnet

volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge
