definitions:
  controllers.Post:
    properties:
      body:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      title:
        type: string
      updatedAt:
        type: string
      userId:
        type: integer
    type: object
info:
  contact: {}
paths:
  /posts:
    get:
      consumes:
      - application/json
      description: get post list
      operationId: get-post-list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.Post'
            type: array
      summary: get post list
      tags:
      - post
  /posts/{postId}:
    get:
      consumes:
      - application/json
      description: get post by id
      operationId: get-post-by-id
      parameters:
      - description: Post ID
        in: path
        name: postId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Post'
      summary: get post by id
      tags:
      - post
swagger: "2.0"
