definitions:
  controllers.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  controllers.Post:
    properties:
      body:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      title:
        type: string
      update_at:
        type: string
      user_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /posts:
    get:
      consumes:
      - application/json
      description: get post list
      operationId: get-post-list
      parameters:
      - description: 件数 未実装です。
        in: query
        name: limit
        type: string
      - description: 開始位置 未実装です。
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.Post'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: get post list
      tags:
      - post
    post:
      consumes:
      - application/json
      description: create post
      operationId: create-post
      parameters:
      - description: タイトル (最大100文字)
        in: query
        name: title
        required: true
        type: string
      - description: 本文
        in: query
        name: body
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Post'
        "400":
          description: タイトルは100文字以下である必要があります。
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "401":
          description: 認証が必要です。
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: create post
      tags:
      - post
  /posts/{postId}:
    get:
      consumes:
      - application/json
      description: get post by id
      operationId: get-post-by-id
      parameters:
      - description: Post ID デフォルトで1から2までしかデータがありません。
        in: path
        name: postId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Post'
        "400":
          description: 不正なpostID
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "404":
          description: ポストが見つからない
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: get post by id
      tags:
      - post
swagger: "2.0"
